### ISSUE TITLE
Einstellungen überarbeiten

### ISSUE THREAD

**Issue by StoppedwummSites** [Stoppedwumm-Studios/STScenes#6]

**Comment by StoppedwummSites** [comment]
We are working at  it, we will start working in a hour or tommorow on it.

# Thank you for your patience

**Comment by Stoppedwumm** [comment]
# God no, I'm not doing that today you Work Monster
## Also I don't really want to do this but its to 16.12.2023 so
### I'm doin it tomorrow
crem

**Comment by StoppedwummSites** [comment]
# Too bad that I'm maybe skipping it bc I have another project
## That's why its in review

**Comment by StoppedwummSites** [comment]
# Ha, not today
